apiVersion: v1
entries:
  krabka-operator:
  - apiVersion: v2
    appVersion: 0.4.0
    created: "2026-09-24T08:19:18.219625202Z"
    description: Kubernetes operator for Krabka clusters
    digest: 096120cad1c14696df0ae10f69c9ab1da5c22209a3ee393fad1c85ac5d132f7d
    home: https://github.com/krabka-io/krabka-operator
    icon: https://krabka-io.github.io/logo.png
    keywords:
    - kafka
    - krabka
    - operator
    kubeVersion: '>= 1.28.0-0'
    maintainers:
    - name: The Krabka Authors
    name: krabka-operator
    sources:
    - https://github.com/krabka-io/krabka-operator
    type: application
    urls:
    - https://krabka.io/charts/krabka-operator-0.4.0.tgz
    version: 0.4.0
  krabka-rebalancer:
  - apiVersion: v2
    appVersion: 0.4.0
    created: "2026-09-24T08:19:18.220176934Z"
    description: Cruise-Control-equivalent partition rebalancer for Krabka clusters.
    digest: 85bb9ebfe0adc351a05dbb884150557f2c79cdda8e0ffcefecaabebe29b8efb4
    home: https://github.com/krabka-io/krabka-rebalancer
    icon: https://krabka-io.github.io/logo.png
    name: krabka-rebalancer
    sources:
    - https://github.com/krabka-io/krabka-rebalancer
    type: application
    urls:
    - https://krabka.io/charts/krabka-rebalancer-0.4.0.tgz
    version: 0.4.0
  krabka-schema-registry:
  - apiVersion: v2
    appVersion: 0.4.0
    created: "2026-09-24T08:19:18.220589581Z"
    description: Confluent Schema Registry-compatible service for Krabka
    digest: 499daf7143445a01974d4b08287b23c68ab23487cdbaf09e95dd301131d416fd
    home: https://github.com/krabka-io/krabka-schema-registry
    icon: https://krabka-io.github.io/logo.png
    keywords:
    - kafka
    - krabka
    - schema-registry
    kubeVersion: '>= 1.28.0-0'
    maintainers:
    - name: The Krabka Authors
    name: krabka-schema-registry
    sources:
    - https://github.com/krabka-io/krabka-schema-registry
    type: application
    urls:
    - https://krabka.io/charts/krabka-schema-registry-0.4.0.tgz
    version: 0.4.0
generated: "2026-09-24T08:19:18.2181195Z"
