apiVersion: v1
entries:
  krabka-operator:
  - apiVersion: v2
    appVersion: 0.4.0
    created: "2026-09-14T08:45:42.135710371Z"
    description: Kubernetes operator for Krabka clusters
    digest: 8621b624fd77e51aba0f3b2f8cb7f99968afcc5362efeb201ce613490f1faabc
    home: https://github.com/krabka-io/krabka-operator
    icon: https://krabka-io.github.io/logo.png
    keywords:
    - kafka
    - krabka
    - operator
    kubeVersion: '>= 1.28.0-0'
    maintainers:
    - name: The Krabka Authors
    name: krabka-operator
    sources:
    - https://github.com/krabka-io/krabka-operator
    type: application
    urls:
    - https://krabka.io/charts/krabka-operator-0.4.0.tgz
    version: 0.4.0
  krabka-rebalancer:
  - apiVersion: v2
    appVersion: 0.4.0
    created: "2026-09-14T08:45:42.136280263Z"
    description: Cruise-Control-equivalent partition rebalancer for Krabka clusters.
    digest: ceab94822f8ac3a07b7be793cf6a93f963ba9c97856dbf5f8019c546c805df76
    home: https://github.com/krabka-io/krabka-rebalancer
    icon: https://krabka-io.github.io/logo.png
    name: krabka-rebalancer
    sources:
    - https://github.com/krabka-io/krabka-rebalancer
    type: application
    urls:
    - https://krabka.io/charts/krabka-rebalancer-0.4.0.tgz
    version: 0.4.0
  krabka-schema-registry:
  - apiVersion: v2
    appVersion: 0.4.0
    created: "2026-09-14T08:45:42.13670432Z"
    description: Confluent Schema Registry-compatible service for Krabka
    digest: e25da51c94138d79e7b03489f98e41bf80afc3395ad62374bf4053432ed93530
    home: https://github.com/krabka-io/krabka-schema-registry
    icon: https://krabka-io.github.io/logo.png
    keywords:
    - kafka
    - krabka
    - schema-registry
    kubeVersion: '>= 1.28.0-0'
    maintainers:
    - name: The Krabka Authors
    name: krabka-schema-registry
    sources:
    - https://github.com/krabka-io/krabka-schema-registry
    type: application
    urls:
    - https://krabka.io/charts/krabka-schema-registry-0.4.0.tgz
    version: 0.4.0
generated: "2026-09-14T08:45:42.134227499Z"
