apiVersion: v1
entries:
  krabka-operator:
  - apiVersion: v2
    appVersion: 0.4.0
    created: "2026-09-12T23:24:39.809169138Z"
    description: Kubernetes operator for Krabka clusters
    digest: 08bb39674cf4039cbe0cced515dc19e0b686c645f1890f7fc2f41b872898e9f6
    home: https://github.com/krabka-io/krabka-operator
    icon: https://krabka-io.github.io/logo.png
    keywords:
    - kafka
    - krabka
    - operator
    kubeVersion: '>= 1.28.0-0'
    maintainers:
    - name: The Krabka Authors
    name: krabka-operator
    sources:
    - https://github.com/krabka-io/krabka-operator
    type: application
    urls:
    - https://krabka-io.github.io/charts/krabka-operator-0.4.0.tgz
    version: 0.4.0
  krabka-rebalancer:
  - apiVersion: v2
    appVersion: 0.4.0
    created: "2026-09-12T23:24:39.809707574Z"
    description: Cruise-Control-equivalent partition rebalancer for Krabka clusters.
    digest: acd0c725110354bc4d615aeff9079ddac4f7be81f3111aab59aeae3528c5690c
    home: https://github.com/krabka-io/krabka-rebalancer
    icon: https://krabka-io.github.io/logo.png
    name: krabka-rebalancer
    sources:
    - https://github.com/krabka-io/krabka-rebalancer
    type: application
    urls:
    - https://krabka-io.github.io/charts/krabka-rebalancer-0.4.0.tgz
    version: 0.4.0
  krabka-schema-registry:
  - apiVersion: v2
    appVersion: 0.4.0
    created: "2026-09-12T23:24:39.810122376Z"
    description: Confluent Schema Registry-compatible service for Krabka
    digest: 0924484db1bfc20c32ff7408ad610cd22ce71b2afccb0ee9d07fbef9e94d3ff5
    home: https://github.com/krabka-io/krabka-schema-registry
    icon: https://krabka-io.github.io/logo.png
    keywords:
    - kafka
    - krabka
    - schema-registry
    kubeVersion: '>= 1.28.0-0'
    maintainers:
    - name: The Krabka Authors
    name: krabka-schema-registry
    sources:
    - https://github.com/krabka-io/krabka-schema-registry
    type: application
    urls:
    - https://krabka-io.github.io/charts/krabka-schema-registry-0.4.0.tgz
    version: 0.4.0
generated: "2026-09-12T23:24:39.807580329Z"
