[main]
loadpath = "/share/stdlib"
loadpath = "/packages"
magic = 14
memlimit = 1000
running_provers_max = 1
timelimit = 5

[prover]
command = "alt-ergo %f"
driver = "/try_alt_ergo.drv"
editor = ""
in_place = false
interactive = false
name = "Alt-Ergo"
shortcut = "alt-ergo"
version = "2.6.2"
