[main]
loadpath = "/share/stdlib"
loadpath = "/packages"
magic = 14
memlimit = 1000
running_provers_max = 1
timelimit = 5

[prover]
command = "alt-ergo %f"
driver = "/try_alt_ergo.drv"
editor = ""
in_place = false
interactive = false
name = "Alt-Ergo"
shortcut = "alt-ergo"
version = "2.6.2"

[prover]
command = "z3 %f"
driver = "/share/drivers/z3_4_12.drv"
editor = ""
in_place = false
interactive = false
name = "Z3"
shortcut = "z3"
version = "4.15.3"

[prover]
command = "cvc5 %f"
driver = "/share/drivers/cvc5.drv"
editor = ""
in_place = false
interactive = false
name = "CVC5"
shortcut = "cvc5"
version = "1.3.1"
